-- 품종 넣기

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '가지/오이');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '무/당근');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '민속채소');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '배추/양배추');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '부추');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '시금치');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '쌈채소');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '참외/수박');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '콩/옥수수');

INSERT INTO "SEED_TYPE"
VALUES(SEQ_SEED_CODE.NEXTVAL, '호박');



COMMIT;

ROLLBACK;

SELECT * FROM MEMBER;



-- 씨앗 넣기

-- 계정 추가
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '유저일', 'user01@kh.com',
			NULL, '01011112222', DEFAULT, DEFAULT, DEFAULT);



COMMIT;
-- 유저일 비밀번호 
-- pass01 을 암호화된 $2a$10$2p01wv0FlCOJkGRcZCl.lOPXd1kYpmgxBNCZwdSNXiVzeQgthQuwe 로 업데이트
UPDATE "MEMBER" SET 
MEMBER_PW = '$2a$10$2p01wv0FlCOJkGRcZCl.lOPXd1kYpmgxBNCZwdSNXiVzeQgthQuwe'
WHERE MEMBER_ID = 'user01';

COMMIT;


ROLLBACK;


-- 보드 타입
INSERT INTO "BOARD_TYPE"
VALUES(SEQ_BOARD_CODE.NEXTVAL, '자유 게시판');

INSERT INTO "BOARD_TYPE"
VALUES(SEQ_BOARD_CODE.NEXTVAL, '문의 게시판');

INSERT INTO "BOARD_TYPE"
VALUES(SEQ_BOARD_CODE.NEXTVAL, '팁과 노하우');



SELECT * FROM BOARD_TYPE bt ;

SELECT * FROM MEMBER;

SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N'
AND MEMBER_ID = 'user01';

