-- 계정 추가
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '유저일', 'user01@kh.com',
			NULL, '010-1111-2222', DEFAULT, DEFAULT, DEFAULT);

-- 유저일 비밀번호 
-- pass01 을 암호화된 $2a$10$2p01wv0FlCOJkGRcZCl.lOPXd1kYpmgxBNCZwdSNXiVzeQgthQuwe 로 업데이트
UPDATE "MEMBER" SET 
MEMBER_PW = '$2a$10$2p01wv0FlCOJkGRcZCl.lOPXd1kYpmgxBNCZwdSNXiVzeQgthQuwe'
WHERE MEMBER_ID = 'user01';


SELECT * FROM "MEMBER";

-- 계정 추가
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '유저이', 'user02@kh.com',
			NULL, '010-2222-2222', DEFAULT, DEFAULT, DEFAULT);

-- 유저일 비밀번호 
-- pass01 을 암호화된 $2a$10$2p01wv0FlCOJkGRcZCl.lOPXd1kYpmgxBNCZwdSNXiVzeQgthQuwe 로 업데이트
UPDATE "MEMBER" SET 
MEMBER_PW = '$2a$10$2p01wv0FlCOJkGRcZCl.lOPXd1kYpmgxBNCZwdSNXiVzeQgthQuwe'
WHERE MEMBER_ID = 'user02';


COMMIT;


-- 게시글 샘플 ALT + X 로 실행
-- ******* 아직 실행 안함 내용 수정하고 진행 ********
BEGIN
	FOR I IN 1..600 LOOP
		
		INSERT INTO "BOARD"
		VALUES(SEQ_BOARD_NO.NEXTVAL,
					 SEQ_BOARD_NO.CURRVAL || '번째 게시글',
					 SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다',
					 DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
					 CEIL( DBMS_RANDOM.VALUE(0,5) ), -- MEMBER_NO(작성회원번호)
					 3 -- BOARD_CODE(게시판종류)
		);
		
	END LOOP;
END;

COMMIT;

SELECT * FROM BOARD_IMG ;

SELECT * FROM "MEMBER";

-- [1] 자유 게시판 샘플 
-- ******* 아직 실행 안함 내용 수정하고 진행 ********
BEGIN
	FOR I IN 1..300 LOOP
	
		INSERT INTO "COMMENT"	
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT, DEFAULT,
			CEIL( DBMS_RANDOM.VALUE(0, 500) ), -- 게시글번호
			CEIL( DBMS_RANDOM.VALUE(0,3) ), -- 댓글작성회원번호
			NULL -- 부모댓글번호
		);
	END LOOP;
END;

-- [2] 문의 게시판 샘플
-- ******* 아직 실행 안함 내용 수정하고 진행 ********
BEGIN
	FOR I IN 1..1 LOOP
	
		INSERT INTO "COMMENT"	
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT, DEFAULT,
			1806, -- 게시글번호
			4, -- 댓글작성회원번호
			1 -- 부모댓글번호
		);
	END LOOP;
END;

-- [3] 팁과 노하우 게시판 샘플
-- ******* 아직 실행 안함 내용 수정하고 진행 ********
BEGIN
	FOR I IN 1..300 LOOP
	
		INSERT INTO "COMMENT"	
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT, DEFAULT,
			CEIL( DBMS_RANDOM.VALUE(0, 500) ), -- 게시글번호
			CEIL( DBMS_RANDOM.VALUE(0,3) ), -- 댓글작성회원번호
			NULL -- 부모댓글번호
		);
	END LOOP;
END;


COMMIT;

SELECT * FROM "COMMENT";


SELECT * FROM "MEMBER";
SELECT * FROM "BOARD_LIKE";
SELECT * FROM "BOARD"
WHERE BOARD_CODE = 2
ORDER BY BOARD_NO DESC;


SELECT * FROM SEED_TYPE;

SELECT * FROM SEED;

INSERT INTO "SEED"
(SEED_NO, SEED_NAME, SEED_IMG, SEED_PRICE, SEED_TEMP, SEED_TIME, SEED_DISTANCE, SEED_RATE, SEED_SOLD_OUT,
SEED_CODE, S_IMG_NO)
VALUES(1, '고수', NULL, '1900원, 20~28도', '3~11월', '15cm', '70%', 'N', 3, NULL);





SELECT SEQ_BOARD_IMG_NO.CURRVAL FROM DUAL;


----------------------------- 샘플데이터 끝 -----------------------------------------

SELECT * FROM BOARD;
SELECT * FROM BOARD_IMG;

-- SQL 구문 작성 구역


-- 이전글
SELECT NVL(
	(SELECT BOARD_NO 
	FROM "BOARD"
	WHERE BOARD_CODE = 3
	AND BOARD_NO < 1797
	ORDER BY BOARD_NO DESC
	FETCH FIRST 1 ROW ONLY), -1
)AS BOARD_NO 
FROM "BOARD"
WHERE BOARD_CODE = 3
ORDER BY BOARD_NO DESC
FETCH FIRST 1 ROW ONLY;

-- 다음글
SELECT NVL(
	(SELECT BOARD_NO 
	FROM "BOARD"
	WHERE BOARD_CODE = 3
	AND BOARD_NO > 1807
	ORDER BY BOARD_NO
	FETCH FIRST 1 ROW ONLY), -1
) AS BOARD_NO
FROM "BOARD"
WHERE BOARD_CODE = 3
ORDER BY BOARD_NO
FETCH FIRST 1 ROW ONLY;


SELECT * FROM BOARD_IMG ;
INSERT INTO "BOARD_IMG" VALUES(
	NEXT_BOARD_IMG_NO, '/images/board/', '원본4.jpg', 'test4.jpg', 0, 1818
);

COMMIT;



		SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT,
    
		    (SELECT COUNT(*)
		    FROM "COMMENT" C
		    WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT,
		    
		    (SELECT COUNT(*)
		    FROM "BOARD_LIKE" L
		    WHERE L.BOARD_NO = B.BOARD_NO) LIKE_COUNT,
	    
		    CASE
			    WHEN SYSDATE - BOARD_WRITE_DATE < 1 / 24 / 60
			    THEN FLOOR((SYSDATE - BOARD_WRITE_DATE) * 24 * 60 * 60) || '초 전'
			    
			    WHEN SYSDATE - BOARD_WRITE_DATE < 1 / 24
			    THEN FLOOR((SYSDATE - BOARD_WRITE_DATE) * 24 * 60) || '분 전'
			    
			    WHEN SYSDATE - BOARD_WRITE_DATE < 1
			    THEN FLOOR((SYSDATE - BOARD_WRITE_DATE) * 24) || '시간 전'
			    
			    ELSE TO_CHAR(BOARD_WRITE_DATE, 'YYYY-MM-DD')
			    
			END BOARD_WRITE_DATE,
			
		(SELECT CONCAT(BOARD_IMG_PATH, BOARD_IMG_RENAME)
		 FROM BOARD_IMG
		 WHERE BOARD_NO = B.BOARD_NO
		 AND BOARD_IMG_ORDER = 0) THUMBNAIL
    	  
		FROM "BOARD" B
		JOIN "MEMBER" USING(MEMBER_NO)
		WHERE BOARD_DEL_FL = 'N'
		AND BOARD_CODE = 3
		ORDER BY BOARD_NO DESC;
	
SELECT CONCAT(BOARD_IMG_PATH, BOARD_IMG_RENAME) AS THUMBNAIL
FROM BOARD_IMG
WHERE BOARD_NO = 1822
AND BOARD_IMG_ORDER = 0;
